### PR TITLE
Add ISA_TML and BA_GEST

### PR DESCRIPTION
**Pull request by randombenj**

### CODE REVIEW

**Comment by eddex** [comment]
As I mentioned in #17 

> Add your changes to [tools/parse_module_type.py](https://github.com/eddex/hslu-simple-mep-results/blob/master/tools/parse_module_type.py) **and let the script generate a new version of [data/modules_i.json](https://github.com/eddex/hslu-simple-mep-results/blob/master/data/modules_i.json).** 🐔

**Comment by eddex** [comment]
We have a CONTRIBUTING.md now :) please read

**Comment by randombenj** [comment]
Please fix the formating of the json output of the python script first :)

**Comment by eddex** [comment]
The json files are formatted correctly by the script. Your branch is 37 commits behind, please update your branch.

**Comment by Lextum** [comment]
both modules where added with https://github.com/eddex/hslu-simple-mep-results/commit/281417b2bf7b6758e61eedf138cac8aacfb3dd8a

**Pull request closed without merging**
